[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
campaigning = "5g4EKu74z9AetATqR7LEPfMQwZbQEKGsRJBSxmR6zTLM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
